networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: 'bitnami/postgresql:16.2.0'
    networks:
       - app-tier
    environment:
      - 'POSTGRESQL_DATABASE=restapp'
      - 'POSTGRESQL_PASSWORD=secret'
      - 'POSTGRESQL_USERNAME=user'
      - 'POSTGRESQL_POSTGRES_PASSWORD=secret'
    ports:
      - '15432:5432'
    volumes:
      - 'D:\postgresql:/bitnami/postgresql'
